### ISSUE TITLE
Issues when compiling atm.Abs

### ISSUE THREAD

**Issue by guziy** [mfvalin/modeltools#1]
Hi:

I am not sure if this is a real problem, but I am not able to compile test executables using the latest version of mgi_shm on guillimin. I would like to test it in simple conditions before upgrading the version used in the model:

```
$ make
s.f90 -mpi -DMODEL -DATM f_mgi_test.F90 mgilib2.o -o atm.Abs
USING: /sb/software/areas/armnssm/ssm-domains-base/tools/dev-tools/code-tools_1.0_all/include/Linux_x86-64_pgi11xx/Pre_Compiler_rules
USING: /sb/software/areas/armnssm/ssm-domains-base/tools/dev-tools/code-tools_1.0_all/include/Linux_x86-64_pgi11xx/Common_Compiler_rules
Compiler Rules applied for Linux PGI version 11
USING: /sb/software/areas/armnssm/ssm-domains-base/tools/dev-tools/code-tools_1.0_all/include/Linux_x86-64_pgi11xx/Pre_Compiler_rules
USING: /sb/software/areas/armnssm/ssm-domains-base/tools/dev-tools/code-tools_1.0_all/include/Linux_x86-64_pgi11xx/Common_Compiler_rules
Compiler Rules applied for Linux PGI version 11
f_mgi_test.F90:
/sb/software/areas/armnssm/ssm-domains-base/tools/mpi-tools-el6/openmpi_1.4.4_linux26-x86-64/lib/libmpi.so: undefined reference to `ibv_reg_xrc_rcv_qp@IBVERBS_1.1'
/sb/software/areas/armnssm/ssm-domains-base/tools/mpi-tools-el6/openmpi_1.4.4_linux26-x86-64/lib/libmpi.so: undefined reference to `ibv_close_xrc_domain@IBVERBS_1.1'
/sb/software/areas/armnssm/ssm-domains-base/tools/mpi-tools-el6/openmpi_1.4.4_linux26-x86-64/lib/libmpi.so: undefined reference to `ibv_unreg_xrc_rcv_qp@IBVERBS_1.1'
/sb/software/areas/armnssm/ssm-domains-base/tools/mpi-tools-el6/openmpi_1.4.4_linux26-x86-64/lib/libmpi.so: undefined reference to `ibv_open_xrc_domain@IBVERBS_1.1'
/sb/software/areas/armnssm/ssm-domains-base/tools/mpi-tools-el6/openmpi_1.4.4_linux26-x86-64/lib/libmpi.so: undefined reference to `ibv_modify_xrc_rcv_qp@IBVERBS_1.1'
/sb/software/areas/armnssm/ssm-domains-base/tools/mpi-tools-el6/openmpi_1.4.4_linux26-x86-64/lib/libmpi.so: undefined reference to `ibv_create_xrc_rcv_qp@IBVERBS_1.1'
/sb/software/areas/armnssm/ssm-domains-base/tools/mpi-tools-el6/openmpi_1.4.4_linux26-x86-64/lib/libmpi.so: undefined reference to `ibv_create_xrc_srq@IBVERBS_1.1'
/sb/software/areas/armnssm/ssm-domains-base/tools/mpi-tools-el6/openmpi_1.4.4_linux26-x86-64/lib/libmpi.so: undefined reference to `ibv_query_xrc_rcv_qp@IBVERBS_1.1'
make: *** [atm.Abs] Erreur 2
```

Thanks

**Comment by mfvalin** [comment]
. s.ssmuse.dot dev/pgi-11-s
permet un build (ca utilise openmpi du systeme)
nos vieilles librairies openmpi sont probablement proches de la retraite :-)

[valin@lg-1r17-n03 mgilib_shm]$ . s.ssmuse.dot dev/pgi-11-s
s.ssmuse.dot dev/pgi-11-s
Global tag values:
BUNDLE PATH=@pgi-11-s
USING SHORTCUT
/sb/software/areas/armnssm/ssm-domains-base/setup/v_001/dot-profile-setup_1.0_multi/notshared/data/ssm_domains/ftn/pgi-11-s.sh
BUNDLE PATH=@pgi-11-s
USING SHORTCUT
/sb/software/areas/armnssm/ssm-domains-base/setup/v_001/dot-profile-setup_1.0_multi/notshared/data/ssm_domains/ftn/openmpi-1.6.3.sh
INFO: setting compiling architecture to 'Linux_x86-64/pgi11xx-s'
INFO: module add pgi/11.7
MODULEPATH=/software/CentOS-6/tools/Modules/3.2.9/modulefiles:/home/valin/modulefiles/:/home/armnssm/modulefiles/
INFO: module add openmpi/1.4.3-pgi
MODULEPATH=/software/CentOS-6/tools/Modules/3.2.9/modulefiles:/home/valin/modulefiles/:/home/armnssm/modulefiles/
BUNDLE PATH=@pgi-11-s@base
USING cache for DOMAIN
/sb/software/areas/armnssm/ssm-domains-base/tools/run-tools
BUNDLE PATH=@pgi-11-s@base
USING cache for DOMAIN
/sb/software/areas/armnssm/ssm-domains-base/tools/dev-tools
BUNDLE PATH=@pgi-11-s@base
USING cache for DOMAIN
/sb/software/areas/armnssm/ssm-domains-base/libs/librmn-dev
BUNDLE PATH=@pgi-11-s@base
USING SHORTCUT
/sb/software/areas/armnssm/ssm-domains-base/setup/v_001/dot-profile-setup_1.0_multi/notshared/data/ssm_domains/model_data.sh
BUNDLE PATH=@pgi-11-s@base
USING SHORTCUT
/sb/software/areas/armnssm/ssm-domains-base/setup/v_001/dot-profile-setup_1.0_multi/notshared/data/ssm_domains/rpn_templates.sh
[valin@lg-1r17-n03 mgilib_shm]$ make clean
rm -f mgilib2.o atm.Abs oce.Abs mgi_shm.Abs mpi.Abs
[valin@lg-1r17-n03 mgilib_shm]$ make
s.cc -I. -c -DWITHOUT_GOSSIP -O 2 mgilib2.c -o mgilib2.o
USING:
/sb/software/areas/armnssm/ssm-domains-base/tools/dev-tools/code-tools_1.0_all/include/Linux_x86-64/pgi11xx-s/Pre_Compiler_rules
USING:
/sb/software/areas/armnssm/ssm-domains-base/tools/dev-tools/code-tools_1.0_all/include/Linux_x86-64/pgi11xx-s/Common_Compiler_rules
Compiler Rules applied for Linux PGI version 11
s.f90 -mpi -DMODEL -DATM f_mgi_test.F90 mgilib2.o -o atm.Abs
USING:
/sb/software/areas/armnssm/ssm-domains-base/tools/dev-tools/code-tools_1.0_all/include/Linux_x86-64/pgi11xx-s/Pre_Compiler_rules
USING:
/sb/software/areas/armnssm/ssm-domains-base/tools/dev-tools/code-tools_1.0_all/include/Linux_x86-64/pgi11xx-s/Common_Compiler_rules
Compiler Rules applied for Linux PGI version 11
f_mgi_test.F90:
s.f90 -mpi -DMODEL -DOCE f_mgi_test.F90 mgilib2.o -o oce.Abs
USING:
/sb/software/areas/armnssm/ssm-domains-base/tools/dev-tools/code-tools_1.0_all/include/Linux_x86-64/pgi11xx-s/Pre_Compiler_rules
USING:
/sb/software/areas/armnssm/ssm-domains-base/tools/dev-tools/code-tools_1.0_all/include/Linux_x86-64/pgi11xx-s/Common_Compiler_rules
Compiler Rules applied for Linux PGI version 11
f_mgi_test.F90:
s.f90 f_mgi_test.F90 mgilib2.o -o test.Abs
USING:
/sb/software/areas/armnssm/ssm-domains-base/tools/dev-tools/code-tools_1.0_all/include/Linux_x86-64/pgi11xx-s/Pre_Compiler_rules
USING:
/sb/software/areas/armnssm/ssm-domains-base/tools/dev-tools/code-tools_1.0_all/include/Linux_x86-64/pgi11xx-s/Common_Compiler_rules
Compiler Rules applied for Linux PGI version 11
f_mgi_test.F90:
s.f90 -mpi -DMODEL f_mgi_test.F90 mgilib2.o -o mpi.Abs
USING:
/sb/software/areas/armnssm/ssm-domains-base/tools/dev-tools/code-tools_1.0_all/include/Linux_x86-64/pgi11xx-s/Pre_Compiler_rules
USING:
/sb/software/areas/armnssm/ssm-domains-base/tools/dev-tools/code-tools_1.0_all/include/Linux_x86-64/pgi11xx-s/Common_Compiler_rules
Compiler Rules applied for Linux PGI version 11
f_mgi_test.F90:
s.cc -I. -O 2 -Dmgi_shm=main mgi_shm.c -o mgi_shm.Abs
USING:
/sb/software/areas/armnssm/ssm-domains-base/tools/dev-tools/code-tools_1.0_all/include/Linux_x86-64/pgi11xx-s/Pre_Compiler_rules
USING:
/sb/software/areas/armnssm/ssm-domains-base/tools/dev-tools/code-tools_1.0_all/include/Linux_x86-64/pgi11xx-s/Common_Compiler_rules
Compiler Rules applied for Linux PGI version 11

Michel Valin
analyste de l'informatique
